exclude = ['*', '.*']  # DISABLE
line-length = 99

[lint]
extend-select = [
  "F",    # pyflakes
  "E",    # pycodestyle errors
  "W",    # pycodestyle warnings
  "I",    # isort (import sorting)
  # "N",    # pep8-naming
  # "D",    # pydocstyle
  "UP",   # pyupgrade (drop old / upgrade to new language idioms)
  "YTT",  # flake8-2020 (misuse of sys.version)
  # "ANN",  # flake8annotations
  "S",    # bandit (security rules)
  "BLE",  # blind-except
  "B",    # bugbear (likely bug identifier)
  "A",    # builtin shadowing
  # "CPY",  # copyright (check for copyright notice on all files)
  "C4",   # comprehensions
  "DTZ",  # datetimez
  "T10",  # debugger (detect traces)
  # "EM",   # errmsg (conventions for improving tracebacks)
  "EXE",  # executable (shebang/exec-bit issues)
  "FA",   # future-annotations
  "ISC",  # implicit-str-concat
  "ICN",  # import-conventions
  "G",    # logging-format
  "PT",   # pytest-style
  "Q",    # quotes (consistent quotes style)
  "NPY",  # Numpy-specific rules
  "RUF",  # Ruff-specific rules
]
extend-ignore = [
  "S311",    # We are not using random for cryptographic purposes
  "S603",    # Too noisy, rarely anything to do
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "ISC001",
  "ISC002",
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.extend-per-file-ignores]
"*/test_*.py" = ["S101"]
"docs/conf.py" = ["A001"]
"docs/sphinxext/github_link.py" = ["BLE001"]

[format]
quote-style = "single"
docstring-code-format = true
